In [1]:
# SQL Alchemy
from sqlalchemy import create_engine
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()
#import config file
from config import user, pwd
#import dependencies
import numpy as np
import pandas as pd
from pprint import pprint

In [2]:
# Create Engine and Pass in MySQL Connection
engine = create_engine(f"mysql://root:{pwd}@localhost/letour_db")
conn = engine.connect()
# Create our session (link) from Python to the DB
session = Session(engine)

In [3]:
Base=automap_base()
Base.prepare(engine, reflect=True)
Base.classes.keys()

['race',
 'race_result_type',
 'race_results',
 'race_starters',
 'race_stages',
 'race_teams']

In [4]:
Race = Base.classes.race
Type = Base.classes.race_result_type
Results = Base.classes.race_results
Stages = Base.classes.race_stages
Starters = Base.classes.race_starters

In [19]:
sel=[Results.rider_id, Starters.rider_name, Starters.rider_country, Results.stage_id,  Results.ranking, Results.race_result_type_id, Starters.rider_team]

my_list =[1, 8, 11, 21, 51, 61, 71, 75, 78, 81, 91, 141, 161, 166]
results=session.query(*sel).join(Starters, isouter=True)\
.filter(Results.race_result_type_id==2)\
.filter(Results.rider_id.in_(my_list)).all()
df=pd.DataFrame(results, columns=["rider_id", "rider_name", "rider_country", "stage_id", "ranking", "race_result_type_id", "rider_team"])
riders=df.drop_duplicates(subset="rider_id", keep="first")
riders= riders[["rider_id", "rider_name", "rider_country", "stage_id", "ranking"]]
riders

     rider_id          rider_name  rider_country  stage_id  ranking
0           1        Chris Froome  Great Britain         1       91
24          8      Geraint Thomas  Great Britain         1       15
48         11      Rigoberto Urán       Colombia         1       44
62         21       Romain Bardet         France         1       35
86         51     Vincenzo Nibali          Italy         1       12
101        61          Adam Yates  Great Britain         1       84
125        71      Nairo Quintana       Colombia         1      112
149        75         Mikel Landa          Spain         1       33
173        78  Alejandro Valverde          Spain         1       38
197        81        Richie Porte      Australia         1       83
208        91       Daniel Martin        Ireland         1       52
232       141       Ilnur Zakarin         Russia         1       43
256       161   Steven Kruijswijk    Netherlands         1       42
280       166       Primoz Roglic       Slovenia         1       54

In [27]:
data=[]
for row in riders.iterrows():
    riderData = {}
    riderData['rider_id'] = row[1][0]
    riderData['name'] = row[1][1]
    riderData['country'] = row[1][2]
    riderData['performance'] = {
        'stages': df.loc[df.rider_id == row[1][0]].stage_id.tolist(),
        'rank': df.loc[df.rider_id == row[1][0]].ranking.tolist()
    }
    data.append(riderData)
data

[{'rider_id': 1,
  'name': 'Chris Froome',
  'country': 'Great Britain',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [91,
    76,
    18,
    91,
    76,
    18,
    17,
    15,
    14,
    14,
    12,
    8,
    6,
    2,
    2,
    2,
    2,
    2,
    2,
    3,
    3,
    4,
    3,
    3]}},
 {'rider_id': 8,
  'name': 'Geraint Thomas',
  'country': 'Great Britain',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [15,
    6,
    3,
    15,
    6,
    3,
    3,
    4,
    2,
    2,
    2,
    2,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1]}},
 {'rider_id': 11,
  'name': 'Rigoberto Urán',
  'country': 'Colombia',
  'performance': {'stages': [1, 2, 3, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
   'rank': [44, 29, 10, 44, 29, 10, 10, 9, 7, 7, 6, 22, 22, 30]}},
 {'rider_id': 21,
  'name': 'Romain Bardet',
  'country': 'France',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [35,
    22,
    25,
    35,
    22,
    25,
    20,
    18,
    23,
    23,
    22,
    17,
    14,
    8,
    6,
    5,
    5,
    5,
    5,
    8,
    8,
    7,
    6,
    6]}},
 {'rider_id': 51,
  'name': 'Vincenzo Nibali',
  'country': 'Italy',
  'performance': {'stages': [1, 2, 3, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
   'rank': [12, 21, 22, 12, 21, 22, 19, 17, 16, 16, 15, 12, 9, 4, 4]}},
 {'rider_id': 61,
  'name': 'Adam Yates',
  'country': 'Great Britain',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [84,
    73,
    20,
    84,
    73,
    20,
    18,
    16,
    13,
    13,
    13,
    9,
    7,
    16,
    22,
    21,
    27,
    30,
    27,
    29,
    29,
    30,
    29,
    29]}},
 {'rider_id': 71,
  'name': 'Nairo Quintana',
  'country': 'Colombia',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [112,
    99,
    59,
    112,
    99,
    59,
    48,
    33,
    27,
    27,
    26,
    21,
    16,
    9,
    9,
    8,
    8,
    8,
    8,
    5,
    5,
    9,
    10,
    10]}},
 {'rider_id': 75,
  'name': 'Mikel Landa',
  'country': 'Spain',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [33,
    32,
    17,
    33,
    32,
    17,
    16,
    14,
    12,
    12,
    11,
    10,
    8,
    7,
    7,
    6,
    6,
    6,
    6,
    7,
    7,
    6,
    7,
    7]}},
 {'rider_id': 78,
  'name': 'Alejandro Valverde',
  'country': 'Spain',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [38,
    20,
    16,
    38,
    20,
    16,
    15,
    13,
    8,
    8,
    7,
    5,
    3,
    11,
    12,
    11,
    11,
    11,
    11,
    11,
    11,
    14,
    14,
    14]}},
 {'rider_id': 81,
  'name': 'Richie Porte',
  'country': 'Australia',
  'performance': {'stages': [1, 2, 3, 1, 2, 3, 4, 5, 6, 7, 8],
   'rank': [83, 71, 14, 83, 71, 14, 14, 12, 11, 11, 10]}},
 {'rider_id': 91,
  'name': 'Daniel Martin',
  'country': 'Ireland',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [52,
    40,
    39,
    52,
    40,
    39,
    33,
    24,
    21,
    21,
    31,
    24,
    17,
    10,
    10,
    9,
    10,
    10,
    10,
    9,
    9,
    8,
    8,
    8]}},
 {'rider_id': 141,
  'name': 'Ilnur Zakarin',
  'country': 'Russia',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [43,
    28,
    15,
    43,
    28,
    15,
    42,
    29,
    25,
    25,
    24,
    19,
    18,
    13,
    14,
    13,
    13,
    13,
    14,
    12,
    12,
    10,
    9,
    9]}},
 {'rider_id': 161,
  'name': 'Steven Kruijswijk',
  'country': 'Netherlands',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [42,
    37,
    26,
    42,
    37,
    26,
    22,
    20,
    20,
    20,
    20,
    16,
    12,
    6,
    8,
    7,
    7,
    7,
    7,
    6,
    6,
    5,
    5,
    5]}},
 {'rider_id': 166,
  'name': 'Primoz Roglic',
  'country': 'Slovenia',
  'performance': {'stages': [1,
    2,
    3,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21],
   'rank': [54,
    39,
    27,
    54,
    39,
    27,
    21,
    19,
    17,
    17,
    16,
    13,
    10,
    5,
    5,
    4,
    4,
    4,
    4,
    4,
    4,
    3,
    4,
    4]}}]